### ISSUE TITLE
无法运行起来

### ISSUE THREAD

**Issue by lcjnil** [miserylee/Plugit#1]
node: v6.3.0

`npm run dev` 报 `ERROR in Cannot find module 'postcss-modules-values'`，怀疑是和 css-modules 有关，但是没有做更详细的测试。

另外在 webpack.config 里面，less 把 `autoprefixer` load 了两遍。

其实是很想看看这个项目的 demo，但是没能跑起来。
另外，我看到 build 目录下也用了 bower，所以这个项目的 package.json 里面也应该写下 bower？以及现在 bower 是逐渐被淘汰的，完全可以用 npm 代替。

**Comment by miserylee** [comment]
这几个问题主要都是集中在Plugit的管理面板这部分。

1. 可以直接执行`npm start`这部分是启动Plugit的Example服务器，dev配置主要是启动管理面板的开发服务器，这一部分并不是主要的。
2. `postcss-modules-values`这个依赖的问题可能是开发过程中遗留的问题，因为在使用React+Redux+webpack开发过程中，尝试过很多东西，这个我后面排查一下是哪个依赖的问题。
3.  less load两遍`autoprefixer`是手残了，已经改正，后面commit
4. bower在这里只是依赖了一个`material-design-icons`图标库，主要是因为npm没有这个库，也有可能是我没找到_(:з」∠)_。

**Comment by lcjnil** [comment]
1. 没有提供 seed database，需要手动来搞个 user
2. 魔改了一下 css-loader 之后这个问题解决了，然而说实话没有看懂前端……
4. https://www.npmjs.com/package/material-design-icons 

刚才稍微跑了一下 demo，说实话并没有理解是什么意思……

**Comment by miserylee** [comment]
1. 有一个创建超级管理员的接口，只是没在前端做，这个后面会改进。
2. 这个框架重点不是前端，前端只是对组件和插件的管理，而且还是个半成品。
3. 这个装过一次，报shasum错误，官方的包可能有问题，所以才会放弃。

Plugit主要功能是组件模块和插件模块的热拔插，逻辑组件化可以让开发过程更加简洁。这个因为现在没空写文档，所以看起来会比较懵，后期会补上文档:D
